spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
---
spring:
  profiles: test
  application:
    name: springcloud-config-test
2321321321你老豆大撒旦撒多撒多撒撒
